[build]
   command = "CI= npm run build"
   publish="/build"

[[redirects]]
  from = "/api/*"
  to = "http://apis.data.go.kr/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200